# Watch iteration -1

**Things to cover how are arrays sored in memory , broadcastig rules**

In [9]:
import numpy as sex # import library as alias(this is what ever name you want to give)

In [18]:
# how to define an array in python using numpy
my_array = sex.array([1,2,3,4]) # variable name of array = lib_name.array.([])
print(my_array)
print(type(my_array)) # This is no longer a list this is a ndarry( n-dimensional array)

[1 2 3 4]
<class 'numpy.ndarray'>


lets breakdown everything

my_array = we are assigning name of the variable array in which we will store it 

sex = this is the alias we used for numpy so basically it is numpy.

.array() = so traditionally .xyz means that we are calling method or we are calling function available in only that data type 
         similarly here we are calling functions which are available in numpy library hence we are using sex.array() so its 
         just a functin which is available in the numpy lib

([1,2,3,4]) =  so we are passing argument in the numpy function here and the argument is a list 
so this is how we are storing array in python using numpy. We can also use array lib to store array

In [1]:
# lets make our learning environment clean and not use profane words 
import numpy as np

In [2]:
lis = [1,2,3,4]
ad = np.add(lis)
print(ad)

TypeError: add() takes from 2 to 3 positional arguments but 1 were given

In [3]:
print(np.add(3,6)) # not taking 3 arguments
# it can take more than 3 argumnets
# no it does not take more then two arguments 

9


In [6]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
array3 = np.array([9,10,11,12])
array4 = np.array([13,14,15,16])
array5 = np.array([17,18,19,20])
print(np.add(array1,array2,array3,array4,array5))

TypeError: add() takes from 2 to 3 positional arguments but 1 were given

In [4]:
# lets create an array first 
'''There are two methods to create an array one is np.array() and the other is np.asarray() in both of them you can pass a dtype
i.e what datatype you want the array to be in default is int '''
l = [1,2,3,4]
print(np.array(l))
print(np.asarray(l,dtype = float)) # s


[1 2 3 4]
[1. 2. 3. 4.]


# Lets create a 0-d array 

In [3]:
arr = np.array(1) # a single element are generally 0-d
print(arr)
arr.ndim

1


0

# Lets create a 1- D array 

In [5]:
my_array_1 = np.array([1,2,3,1,5,6])
print(my_array_1)

# This is 1-D array it is a list inside array function 

[1 2 3 1 5 6]


1

# Lets create a 2- D array
 We have create [ [ ] , [ ] ] which is a nested list or we can say a list in a list . A list in a list is called 2-d array 
 
 We can also say that **collection of 1-d array is 2-d array**

In [15]:
my_array_2 = np.array([[1,2,3],[24,2,5]])
print(my_array_2)
my_array_2.shape
# mind the square brackets its a list in a list that is square brackets in square brackets to avoid error

[[ 1  2  3]
 [24  2  5]]


(2, 3)

# Let's create a 3-d array

3-d array is basically a collection of 2-d arrays

how shall you create the array 

Well start by creating 1-d then 2-d and then 3-d


In [5]:
my_array_3 = np.array([[[1,2,3],[24,2,5]],[[4,5,6],[7,8,9]]])
print(my_array_3)
# np.shape(my_array_3)


[[[ 1  2  3]
  [24  2  5]]

 [[ 4  5  6]
  [ 7  8  9]]]


# let's create a 4-d array
A 4-d array is a collection of 3-d array 

In [31]:
my_array_4 = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[9,10],[11,12]],[[13,14],[15,16]]]])
print(my_array_4)
my_array_4.shape

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


(2, 2, 2, 2)

In [9]:
np.array([]).ndim # this takes [] as a empty sequence of no number hence this is 1 dimension

1

In [12]:
np.array(14343).ndim # this takes the value 14343 as an individual number with no other sequence

0

**why us np.array([]) is 1 dimension and np.array(11) is zero dimension ?**

np.array([]) creates an empty array with one dimension, while np.array(1) creates a zero-dimensional array containing the value 1. This is because the input to the np.array() function is interpreted as a nested sequence of objects, where each level of nesting corresponds to one dimension of the resulting array. In the case of np.array([]), the input is an empty sequence, which is interpreted as a one-dimensional array with zero elements. In the case of np.array(1), the input is not a sequence, so it is interpreted as a zero-dimensional array containing a single element.

A nested sequence of objects refers to a sequence that contains other sequences as its elements. Each level of nesting corresponds to one dimension of the resulting array. For example, if you pass a list of lists to the np.array() function, it will create a two-dimensional array where the outer list represents the rows and the inner lists represent the columns. Similarly, if you pass a list of lists of lists, it will create a three-dimensional array, and so on.

## Note: To find the dimension of array - count the no. of square brackets you have to remove to reach to the first element 

# Some methods in array 

shape - So what exactly does the spape method do 

It basically tells us the structure of the array 
so it works like this suppose you have to find the shape of a 3-d array so 3-d array will be made of combination of 2-d arrays 
so the first element in the tuple will give you the no. 2-d array element in the array , the second element in the tulple will give the no. of 1-d array and the third will give the no. of element in the 1-d array so your output will be like (a,b,c)

note - 1-d array will have o/p - (a,) where a is no. of elements inside the array. No. of elements in the tuple is the dimension of the array

2-d array will have o/p - (a,b) where a is the no. of 1-d array , b is the no. of element in 1-d array and dimension of array is the number of elements in the tuple here the tuple has a,b i.e 2 elements hence the dim is 2

3-d array will have o/p - (a,b,c) where a is the no. of 2-d array, b is the no. of 1-d array & c is the elements in the 1-d arr
The dimension is 3 as there are three elements in the tuple 

4-d array will have o/p - (a,b,c,d) where a is the no. of 3-day array, b is the no. of 2-d array , c is the no of 1-d array and 
d is the no. of element in 1 d array. And the dimension of this array will be 4 as there are 4 elements in the tuple

**Also the no. of elements in the tuple(in the o/p) is the dimension of the array** 

In [10]:
# finding the shape of array 
arr1 = np.array([1,2,3,3,5])
print(arr1.shape) # so 1-d is collection of elemetns hence out put in no. of elements inside the array

(5,)


In [12]:
arr2 = np.array([[1,2,3,3,5],[1,2,3,3,5]])
print(arr2.shape) # here this is a 2-d array hence it is a collection of 1-d array. lets understand,it has two 1-D array hence 'a' = 2
# inside the 1-D array it has 5 elements hence 'b' = 5. output is (a,b) = (2,5)

(2, 5)


In [15]:
arr3 = np.array([[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]]])
print(arr3.shape) # it is a 3-d array which means it is a collection of 2-d array. lets check the no. of 2-d arrays, we have 4
#2-d array hence 'a' = 4, Now in 2-d array, 2-d array is it self a collection of 1-d array so there are 2 , 1-d arrays so 'b'
# is 2 , Now the 1 - d is collection of elements lets count the no. of elements in 1-d there are 5 elements 'c'= 5
# hence (a,b,c) = (4,2,5)
# Note since it is giveing there elements in the o/p the dimension of the arr3 is there so just by counting the element of tuple
# we can get the dimensions of the array

(4, 2, 5)


In [7]:
arr4 = np.array([[[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]]],[[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]]]])
print(arr4.shape)
# count the no. of opening square brackets and you will get the dimensions
# now since you know the dimensions you have acquainted your self with the no. of elements in the tuple 
# 4-d is collection of 3-d there are 2, 3-d elements hence 'a'= 2
# 3-d is collection of 2-d there are 2 , 2-d elements hence 'b'= 2
# 2-d is collection of 1-d there are 2 , 1-d elements hence 'c' = 2
# 1-d is collection of elements , there are 5 elements in 1-d hence 'd' = 5

(2, 2, 2, 5)


### ndim method 
the ndim method gives us the dimension of the array

In [22]:
arr_1 = np.array([[1,2,3,3,5],[1,2,3,3,5]])
arr_1.ndim # trick 2 bracket hence 2 dimension


2

### size method 
it gives the no. of elements in the array irrespective of the the square brackets 


In [24]:
#
arr_1 = np.array([[1,2,3,3,5],[1,2,3,3,5]])
arr_1.size

10

In [25]:
arr4 = np.array([[[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]]],[[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]]]])
arr4.size

40

### dtype
it tells us the type of data eg is it a int array, float array etc

In [32]:
arr4 = np.array([[[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]]],[[[1,2,3,3,5],[1,2,3,3,5]],[[1,2,3,3,5],[1,2,3,3,5]]]])
arr4.dtype

dtype('int32')

In [27]:
arr5 = np.array([1,2,3,4,5])
arr5.dtype

dtype('int32')

### astype
it can covert data type into another desired data type

In [34]:
arr6 = np.array([1,2,3,4,5])
arr6.astype(float)
# now it is in decimals

array([1., 2., 3., 4., 5.])

# How to iterate over 2 list simultaneously using to iterators 
while iterating over 2 list you have to use zip method 
    

In [3]:
list_1 = [1,2,3,4,5]
list_2 = [6,7,8,9,10]
emp = []
for i,j in zip(list_1,list_2):
    c = i*j
    emp.append(c)
    print(c) # in step for 

print(emp)  # in list form      

6
14
24
36
50
[6, 14, 24, 36, 50]


In [4]:
# iterating two list using list comprehension
emp = [i*j for i,j in zip(list_1,list_2)] # don't have to assigne any variable here
print(emp)

[6, 14, 24, 36, 50]


### performance perspective
ndarrray takes less time to execute codes 


In [7]:
import time # this is to measure how much time does it take to execute 
size = 1000
list_1 = range(size)
list_2 = range(size)
initial_time = time.time() # it basically note the time 
listy = [i*j for i,j in zip(list_1,list_2)]
# print(listy)
print(time.time()-initial_time)

0.0009980201721191406


In [8]:
import numpy as np
import time 
initial_time= time.time() # note time at the start of the code
array_1 = np.arange(size)
array_2 = np.arange(size)
resultant_array = array_1*array_2
resultant_array
final_time = time.time() # note time at the end of the code
print(final_time-initial_time) 

0.007006645202636719


You can also print the array

In [53]:
size = 10
arr = np.arange(size)
print(arr)
type(arr)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

### Memory perspective 
ndarray takes a lot less memory when compared to list 

In [24]:
# there is a confusion in the sys.getsizeof() method get it cleared 
import sys # module 
list_ = [0,1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(list_)) # it gives the size of the data type and we have multipled it by len(list_) 

152


In [51]:
# ths looks fine
arry = np.array([0,1,2,3,4,5,6,7,8,9])
print(arry.itemsize) # in numpy to get the memory used ,variable.itemsize is used it gives the memory of one element 
print(arry.itemsize*arry.size) # this will give the memory of the entire array

4
40


update your understanding: So basically the itemsize method in sys module gives us the memory size of a **single** datatype in the array the underlying principle or the essence of the sentences are kind of same 

lets understand it with an example 

**Lets understand the itemsize which is limited to numpy in intracacy**

In [11]:
array_1 = np.array([1,2,3,4])
print(f' Memory of datatype int with 4 elements in the array {array_1.itemsize}') # 
array_2 = np.array([1,2,3,4,5,6,7,8,9,0])
print(f' Memory of datatype int with 10 elements in the array {array_2.itemsize}')
# The data type is int here
# The item size of array_1 and array_2 will be same as itemsize method will give the memory size of one element or datatype
array_3 = np.array([1.1,2.2,3.3,4.4])
print(f'Memory of datatype float with 4 elements in the array {array_3.itemsize}')
array_4 = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7,8.8,9.9])
print(f'Memory of datatype float with 10 elements in the array {array_4.itemsize}')
# The item size of array_3 and array_4 will be same as itemsize method will give the memory size of one element or datatype 
# The datatype in this case is float 

 Memory of datatype int with 4 elements in the array 4
 Memory of datatype int with 10 elements in the array 4
Memory of datatype float with 4 elements in the array 8
Memory of datatype float with 10 elements in the array 8


In [37]:
# lets understand the getsizeof method in the sys module 
# lets do it for list first
import sys 
print(f' The memory of empty list is {sys.getsizeof([])}')
print(f'The memory of one element in the list is {sys.getsizeof([1])}')
print(f' The memory of two elements in the list is {sys.getsizeof([1,2])}')
print(f'The memory of ten elements in the list is {sys.getsizeof([1,2,3,4,5,6,7,8,9,9])}')
print(' Every int element in the list has size of 8 bytes')
print('We have also seen that in the above example if we reckon thing the memory of each element comes out to be 9.6 bytes')

 The memory of empty list is 56
The memory of one element in the list is 64
 The memory of two elements in the list is 72
The memory of ten elements in the list is 152
 Every int element in the list has size of 8 bytes
We have also seen that in the above example if we reckon thing the memory of each element comes out to be 9.6 bytes


In [41]:
import numpy as np
emp_list = []
emp_array = np.array(emp_list)
print(emp_array)
print(f'The memory of an empty array is {sys.getsizeof(emp_array)}')
print(f' The memory of one element in the array is {sys.getsizeof(np.array([1]))}')
print(f'The memory of two elements in the array is {sys.getsizeof(np.array([1,2]))}')
print(' We can conclude here that an element in the array occupies around 4bytes of data')
print(f'The memory of ten elements in the array is {sys.getsizeof(np.array([1,2,3,4,5,6,7,8,9,0]))}')


[]
The memory of an empty array is 104
 The memory of one element in the array is 108
The memory of two elements in the array is 112
 We can conclude here that an element in the array occupies around 4bytes of data
The memory of ten elements in the array is 144


**consider bucket and toys**

**sys.getsizeof gives the size of bucket only 
itemsize in np gives the size of the toys only 
I asked this in bingchat**

**So we can come to the conclusion that memory wise the array beats the list, arrays individually takes about half the memory than list**

### functionality perspective  

In [56]:
listy = [1,2,3,4,5] # lets add 4 in every element of the list
listy = listy + 4 # what exactly are we doing here we are adding list data type with element 4 which is bizzare.
print(listy)
# here it throws an error because the plus sign is not a artematic plus rather it is a concatenate sign 
# so in oder to increase the elements in the list we would need to run a code

TypeError: can only concatenate list (not "int") to list

In [58]:
emp = []
for i in listy:
    i += 4
    emp.append(i)
print(emp)    

[5, 6, 7, 8, 9]


In [59]:
# one liner
list_ = [i+4 for i in listy]
print(list_)

[5, 6, 7, 8, 9]


One major advantage of ndarray is you will not have to do this much coding 
lets see what are we talking here

In [4]:
arr = np.array([1,2,3,4,5])
arr = arr + 4 # this is done by broadcasting 
print(arr)
# this is done via broadcasting 

[5 6 7 8 9]


In [67]:
#we cn alos write
listy_1= [1,2,3,4,5,6,7,8,9,0]
arr = np.array(listy_1)
print(arr)


[1 2 3 4 5 6 7 8 9 0]


In [3]:
#and we have this functionlity as well
arr = np.array([1,2,3,4,5])
arr = arr*arr
# this is done by broadcasting 
print(arr)
# this is being done via broadcasting 

[ 1  4  9 16 25]


So are you inquisitive about how this works but before that lets us make ourselves acquainted with the term like vectorizing an array.

"Vectorization" (simplified) is the process of rewriting a loop so that instead of processing a single element of an array N times, it processes (say) 4 elements of the array simultaneously.

So the above code where we added a scalar which is 0-d and value is 4 is done by using broadcasting in numpy 
The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes
there are some rules which the broadcasting follows you can read the documnentation. Here is a link to understand broadcasting in numpy visit https://www.youtube.com/watch?v=0u9OzBSRZec&t=23s


# From chat gpt

**Q. what is vectorization in numpy ?**

Ans. Vectorization is a technique in computer programming in which operations are performed on entire arrays, rather than on individual elements. It is a way of achieving faster and more efficient computations by utilizing the processing power of modern CPUs.

**In the context of NumPy, vectorization refers to the use of functions and operations that are designed to operate on arrays, rather than on individual elements**. For example, you can use the sum function to compute the sum of all the elements in an array, rather than having to loop over the array and add each element separately. This can lead to significant performance improvements, especially for large arrays or when performing a large number of operations.

In [43]:
# Here is an example of how vectorization can be used in NumPy:
import numpy as np

# Create a NumPy array
a = np.array([1, 2, 3, 4])

# Use a vectorized operation to compute the square of each element
b = a**2
print(b)  # Output: [1 4 9 16]

# Use a vectorized function to compute the sum of all the elements
c = np.sum(b)
print(c)  # Output: 30


[ 1  4  9 16]
30


In this example, the ** operator and the sum function are both vectorized operations, meaning that they operate on the entire array a rather than on individual elements. This makes it much faster and more efficient to perform these operations.

**What is broadcasting ?**

**Broadcasting** is a powerful mechanism in NumPy that allows arithmetic operations to be performed on arrays of different shapes. It **allows you to perform operations on arrays of different shapes, as long as they are "broadcastable."**

Broadcastable arrays are arrays that are compatible in their shapes and dimensions. In general, two arrays are broadcastable if the following rules are satisfied:

The arrays have the same number of dimensions.

The shape of the arrays in each dimension is either the same size, or one of the arrays has shape 1 in that dimension.

In [ ]:
#Here is an example of how broadcasting works in NumPy:
import numpy as np

# Create a 2D array with shape (3, 4)
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Create a 1D array with shape (4,)
b = np.array([10, 20, 30, 40])

# Perform an element-wise multiplication using broadcasting
c = a * b
print(c)

# Output:
# [[ 10  40  90 160]
#  [ 50 120 210 320]
#  [ 90 200 330 480]]


In this example, the array **b** is broadcast to the shape of **a** so that the element-wise multiplication can be performed. The resulting array **c** has the same shape as **a**.

Broadcasting is a useful technique that can greatly simplify and speed up your code, especially when working with large arrays. It allows you to perform operations on arrays of different shapes in a concise and efficient manner.

**I have not covered the rules for brodcasting explicitly, Do it if the time premits**

## Here's a tip if you want to pass a matrix in the arguments of the array generators, always start with the no. of rows and column you want in matrix then move on to the no. of matrix you want this will give you a 3-d matrix if you move further, then type in the no. of 3-d matrix bunches you want, this will give you a 4 d matirx

In [9]:
test = np.empty([3,2,3],dtype=int)# np.
print(test)

[[[3801155 5570652 6619251]
  [7536754 4456540 6619237]]

 [[7667824 4259932 7340144]
  [6357060 6357108 4980828]]

 [[6488175 7077985 5505116]
  [7143525     112       0]]]


### Uninttialize array
so while creating an array in the above code to understand how things work in array, it took us time. Here is where the np.empty method in array comes into action. we have to assign the n-dim and dtype it will create an nd-array for us   

In [28]:
# it will give a ndarray with arbitrary elements
auto_array=np.empty((1,2,3), dtype=int) # you can use parenthesis or square brackets, it still works the same 
print(auto_array)
# here the dimension is 3

[[[5242880 5177426 5242957]
  [3997780 6422568 7536737]]]


In [3]:
# you can make all the elements zero by np.zeros
auto_zero = np.zeros([2,2,3],dtype=int) # default values of datatype is float if dtype not passed
print(auto_zero)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [24]:
# you can create an array with all elements as 1
auto_ones = np.ones([3,2,3],dtype=int) # arrgument should be shape and data type 
print(auto_ones)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


# We can change the shape of the array
# Note: We can only do that by keeping in mind that the multiplication of the tuple elments equals to the no. of element

In [34]:
listy = np.array([[1,2,3,4,5],[6,7,8,9,0]]) # total elements here is 10
listy.shape = (10,1) # shapes that we can have is (1,10) ,(10,1),(2,5), (5,2) only
print(listy)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [0]]


# We can create array using arange 
### It works same like range 
np.arange(start_value, end_value, steps, dtype = ' ')
This will give us a 1d array . In order to get a ndarray we will have to exploit the reshape property and convert the 1-d array into n-d array 

Note: While converting the 1-d array into n-d array keep in mind that the dimensions which you want have has to be a factor of elements

In [4]:
rangy=np.arange(5,100,2,dtype = float)
rangy

array([ 5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25., 27., 29.,
       31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51., 53., 55.,
       57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77., 79., 81.,
       83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [11]:
rang=np.arange(5,20,2,dtype = int) # arguments are start value, end value, steps, data type
print(f'This is a one d array: {rang}')
rang.shape = (2,4) # try doing (2,2) it will throw an error why because the factor of elem = 8 is 1 X 8, 2 X 4, 4 x 2, 8 X 1
print('We have converted the 1-d array into 2-d array using arange & shape:',rang)# we can only have the above combination only

This is a one d array: [ 5  7  9 11 13 15 17 19]
We have converted the 1-d array into 2-d array using arange & shape: [[ 5  7  9 11]
 [13 15 17 19]]


## Linspace , its argument are start point , end point , include endpoint, retain steps
We can create an array between defined numbers with steps using linspace method 

Note: The endpoint and the retstep is the parameter which is defined in the function so bear in mind to not do typo there

The number displayed out of the array is the difference between two numbers in the array. This is only displayed when the retain space is set to True 

In [13]:
lin = np.linspace(1, 11, 20, endpoint = True, retstep = True) # The end point will include last value if endpoint is set to true
print(lin) # the steps will be in order if retstep is assigned to true 
# lets understand the 1,11,20 as well 
# 1 lets canvas it as a so a is the lower limit of the numbers in the matrix/array
# 11 lets canvas it as b so b is the upper limit of the numbers in the matrix/array note the upper limit i.e 11 here will not be
# included so basically a no. lower than 11 i.e 10 will be included
# 20 lets canvas this as well to c so c is no of divisions you want between a and b-1 


(array([ 1.        ,  1.52631579,  2.05263158,  2.57894737,  3.10526316,
        3.63157895,  4.15789474,  4.68421053,  5.21052632,  5.73684211,
        6.26315789,  6.78947368,  7.31578947,  7.84210526,  8.36842105,
        8.89473684,  9.42105263,  9.94736842, 10.47368421, 11.        ]), 0.5263157894736842)


# Generate random array using random.random()
# We are going to use this alot in the further operations 

**NOTE**:**use np.random.seed() to preserve the randomness of the array**

In [10]:
# We can also get an array with random numbers using np.random.random()
# Note it gives us the array in float which are between 0.0 and 1.0
# Argument is np.random.random(size=(4,5)) it take both the square and parenthesis i.e size = [4,5]
# also you don't have to mention the keyword size it takes it as default 
random_array = np.random.random([4,5]) # note you have to pass the dimension in (4,5)/[4,5] and not 4,5 like you were doing earlier 
print(random_array) # note the o/p has elements between 0 and 1 only

[[0.7543027  0.71255372 0.39811761 0.22919404 0.71302664]
 [0.05419885 0.13431235 0.92701306 0.44023724 0.44101306]
 [0.99321369 0.51888398 0.92118299 0.92236958 0.0866307 ]
 [0.86938917 0.19307853 0.97557693 0.72248969 0.15333608]]


In [34]:
# if we want array between set numbers than 
random_array_between_number = np.random.randint(1,8, size =(4,5)) # arguments are number between = 1,8 and size = (4,5)
print(random_array_between_number) # the output will not have the last number 8, works just like range in this regard 

[[3 7 4 3 2]
 [6 6 7 6 7]
 [6 6 1 1 4]
 [3 2 7 3 5]]


**Remember we did np.ones and it gave array of only 1 as elements in the array well we can also create an array will equal elements by defining the value of element by np.full() method**

In [30]:
array_user_defined_all_same = np.full((4,4),49)# or we can wirte it as np.full(size = (4,4), fill_value = 49) 
# arguments are shape = (4,4) and fill_value = 49
print(array_user_defined_all_same)

[[49 49 49 49]
 [49 49 49 49]
 [49 49 49 49]
 [49 49 49 49]]


In [29]:
# we can also get the same result via broadcasting 
arr = np.ones((4,4), dtype = int) # argument are shape and dtype 
arr = arr*49
print(arr)


[[49 49 49 49]
 [49 49 49 49]
 [49 49 49 49]
 [49 49 49 49]]


In [37]:
# We can also get identity matxic in the form of square (of course identity matirix are square matrix)
identity_matrix = np.identity(4, dtype = int) # it will atomatically come to know that you want a 4 X 4 matrix
print(identity_matrix) # if you don't give dtype it will take float by default 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [38]:
# you can assign a list into variable and pass that variable to nparray and get aa array 
listy = [1,2,3,4,5]
arr = np.array(listy)
print(arr)

[1 2 3 4 5]


In [39]:
#you can do the same thing with tuple as well 
tup = (1,2,3,4,5,6,7,8,0)
arr_tup = np.array(tup)
print(arr_tup)

[1 2 3 4 5 6 7 8 0]


# Indexing and Slicing in n-d array 

lets understand the difference between indexing and slicing indexing is when you want one element , slicing is when you want a group of element

Lets understand how the indexing workks in 1-d array , 2-D array and 3-D array 

1-d array has the same indexing and slicing as that of list data type 

In [24]:
#lets create a random one dimensional array first 
one_array = np.random.random(5) # takes one argument only that argument is the number of elments you wnat in the array will only
#give one dimensional array 
print(one_array)
print('')
print(one_array[0:3:1]) # this is sclicing in positive direction from 0 till 2 in step of positive 1
print(one_array[3:0:-1]) # this is sciling in negative direction form 3 till 1 in the step of negative 1



[0.27097843 0.69913441 0.12303431 0.84031941 0.00406752]

[0.27097843 0.69913441 0.12303431]
[0.84031941 0.12303431 0.69913441]


**Instead of doing slicing on float lets do it on int value. We can generate a random matrix using the method random.randint(
( )). the argument for the randint are np.random.randint(a,b, size =(c,d)) where a is the lower limit of the value of element you want in the array b is the upper value of element you want in your array, and c,d is actually the size o/p(output) that is it has to be in tuple and** 

In [49]:
# lets do indexing and sclicing 
array_1 = np.random.randint(1,9, size = (9,))
print(array_1)
print(array_1[5]) # we are doing indexing here this will give us only one element at position/index no. 5
print(array_1[2:6]) # we are doing slicing here it will give us a group of elements starting from element at position 2 
#till element at position 5
print(array_1[5:1:-1]) # this is the same sclicing but in negative direction by using step in negaive direction i.e -1

[4 4 8 4 5 4 8 5 8]
4
[8 4 5 4]
[4 5 4 8]


let's now understand how does slicing and indexing happens in 2-d array, the very first thing which we have to keep in mind and (which also falls under note) is that every 2-d array is nothing but a matrix. so in order to pull out only one element from the matrix we will use the concept of the rows and coloums that we already got acquainted with during our matrix and determinent class when we were in 12th grade 

So to pick the single element from the matrix we will have to specify its row and coloum , the row and coloumn corresponds to 
the position of that element in the matrix

**NOTE: THE ROWS START FROM ZERO AND GOES ALL THE WAY UPTO N , THE COLOUMN STARTS FROM ZERO AND GOES ALL THE WAY TILL N**

In [3]:
two_array = np.random.randint(1,10, size = (3,4))
print(two_array)
two_array[1,2] # so this is basically get me the element which is at 2nd row and 3rd coloum and since we know that the rows and
#coloum start form 0 and 0 in array so the index of second row is 1 and the index of 3rd coloum is 2
print('the argument for the index is like (row,coloum) in 2 d matrix')

[[5 2 3 3]
 [4 3 9 5]
 [3 1 6 1]]
the argument for the index is like (row,coloum) in 2 d matrix


In [55]:
two_array[2,3] # ans is worng seed issue

6

**Now lets understand slicing in 2-d array** This concept will also pave the way for us to understand/is a prequisite for slicing in 3-d Now we now that in indexing it takes [rows,coloumn] now what will happend in [slicing of rows , slicing of coloums]
the slicing part will pick bunch of rows together and bunch of coloums together this is what it will look like two_array[0:3,1:3] so what will it do is it will pick the row from 0 till 2 and it will pick coloum from 1 to 2 and will give you all the elements which will lie in the intersection 

In [5]:
two_array[0:3,1:3] 

array([[2, 3],
       [3, 9],
       [1, 6]])

In [4]:
# you can also do that in step in negative directions etc
two_array[-3:,-3:-1] # note since we are not giving the dirction that slicing will happen from positive direction only we will have
# to give the index as per the positive direstion only 
# same o/p but different slicing values 
# you can also use steps to skip alternate rows or coloumn

array([[2, 3],
       [3, 9],
       [1, 6]])

**Note: Since we have created a random matrix every time you import or run the code the matrix will change**

**Now lets understand how does indexing and slicing works in 3-d array**

3-d array are basically collection of 2 day array: let just leave this thing and think how would you pick element form the matrix first you will decide that out of 4 , 2-d matrix from which matrix you want to pick the element, after that you will find the row and coloumn of the matrix and pull the no. out 

This indexing also does the same thing you define the index of the matrix , then in that matrix define row and after that coloumn arr[index, row, coloumn] i would like to remind you here that tha

In [9]:
import numpy as np
arr = np.random.randint(1,10, size = (4,5,5))
print(arr)
print('')
print(arr[0:1,2:3,2:3]) # this will give you in array consider this as more like slicing example
arr[0,2,2] # this will give you in single element

[[[6 9 8 1 7]
  [2 7 3 5 1]
  [2 9 7 3 8]
  [3 9 2 6 8]
  [2 7 6 3 3]]

 [[8 4 2 9 8]
  [7 3 3 8 4]
  [8 2 4 1 5]
  [3 2 5 1 1]
  [3 8 4 1 7]]

 [[6 9 5 4 1]
  [7 9 5 1 1]
  [2 1 6 8 9]
  [5 3 4 8 2]
  [1 3 3 2 5]]

 [[3 5 2 5 9]
  [9 7 9 7 2]
  [3 6 5 9 1]
  [5 9 9 5 5]
  [6 3 6 9 7]]]

[[[7]]]


7

**3-d array slicing**

Now lets see how slicing is done 
so the arr[a,b,c] will be [index, row, coloumn] this will all be in slicing format
if you want that value form two matrix than 
index = select the index of the 2-d matrixs
row = now select the row of selected 2-d matrix in the index ( it will automatically select the rows from 2 matrix)
coloumn = now select the coloumn of selected 2-d matrix in the index ( it will automatically select the coloumn form 2 matrix)

In [11]:
array = np.random.randint(1,7, size = (4,5,5))
print(array)
array[0:3,0:1,0:] # this is [index slicing of  of 2-d matrix, row slicing of all sellected matrix (selected matrix in the index)
#, coloumn slicing of all  selected matrix (selected matrix in the index)]

[[[4 1 3 3 5]
  [3 2 2 6 3]
  [2 4 3 2 3]
  [4 6 6 4 1]
  [4 2 1 2 1]]

 [[6 4 3 1 5]
  [3 5 6 6 3]
  [6 1 2 4 4]
  [1 6 5 4 5]
  [3 6 4 5 6]]

 [[1 5 2 6 4]
  [6 4 3 3 2]
  [6 6 3 5 2]
  [2 6 4 5 1]
  [2 3 3 4 3]]

 [[2 2 3 6 1]
  [4 5 1 4 2]
  [3 6 6 4 5]
  [6 3 6 1 4]
  [5 4 5 2 2]]]


array([[[4, 1, 3, 3, 5]],

       [[6, 4, 3, 1, 5]],

       [[1, 5, 2, 6, 4]]])

** Rough work to understand 3-d array sclicing. You can use assign function to understand the thing more clearly**

In [13]:
#it's a bit confusing but see if you can understand
# For 3-D array slicing the format is array[index,row,column]
a = np.array([[[1,2],[3,4],[5,6]],
             [[7,8],[9,10],[11,12]],
             [[13,14],[15,16],[17,18]]])
print(a)
print('')
print('')
print(a[0:2])
print('')
print(a[0:2,1:])
#print(a[0:2,1:,1:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

[[[ 3  4]
  [ 5  6]]

 [[ 9 10]
  [11 12]]]


In [15]:
#this may help a bit
# lets create a random array
array_1 = np.random.randint(3,8, size = (3,5,4))
print(array_1)
print('')
array_1[0:2,0:2,0:2] = 9999 # this is in the format index of the 2 d , index/slicing of row, indix/slicing of coloum
print(array_1)

[[[4 4 5 3]
  [7 7 7 4]
  [7 5 3 5]
  [3 6 7 3]
  [6 6 6 3]]

 [[4 4 7 4]
  [6 5 6 4]
  [6 7 3 4]
  [6 7 4 4]
  [7 3 7 7]]

 [[3 6 5 4]
  [5 5 6 3]
  [5 3 7 3]
  [7 4 3 5]
  [5 6 6 3]]]

[[[9999 9999    5    3]
  [9999 9999    7    4]
  [   7    5    3    5]
  [   3    6    7    3]
  [   6    6    6    3]]

 [[9999 9999    7    4]
  [9999 9999    6    4]
  [   6    7    3    4]
  [   6    7    4    4]
  [   7    3    7    7]]

 [[   3    6    5    4]
  [   5    5    6    3]
  [   5    3    7    3]
  [   7    4    3    5]
  [   5    6    6    3]]]


In [11]:
array_2 = np.random.randint(1,7, size = (6,5,4))
print(array_2)
array_2[1:4,0:,2:3] # has a format of - (index of 2-d array, rows in general, coloum in general)

[[[3 5 3 3]
  [6 1 3 6]
  [3 1 1 3]
  [6 3 1 4]
  [2 6 4 1]]

 [[4 2 3 3]
  [1 4 6 5]
  [5 6 3 6]
  [6 5 1 6]
  [1 3 4 2]]

 [[1 4 2 3]
  [2 4 5 1]
  [4 3 3 5]
  [5 4 2 1]
  [3 1 5 5]]

 [[6 3 5 5]
  [2 6 2 5]
  [1 5 4 1]
  [3 4 4 6]
  [5 1 1 4]]

 [[3 2 1 2]
  [2 6 1 5]
  [4 6 5 2]
  [5 3 5 1]
  [2 1 6 5]]

 [[1 1 3 1]
  [6 6 5 5]
  [5 5 1 4]
  [2 3 2 1]
  [5 2 3 4]]]


array([[[3],
        [6],
        [3],
        [1],
        [4]],

       [[2],
        [5],
        [3],
        [2],
        [5]],

       [[5],
        [2],
        [4],
        [4],
        [1]]])

In [19]:
#
print(array_2[0:,0,0]) # count of this gives you how many matrix are placed one after the other( into the plane) 
print(array_2[0,0:,0]) #  count of this gives row
print(array_2[0,0,0:]) # count of this gives column
print('')
print(array_2[0])
print('')
print(array_2[0].shape)
print(array_2[0,0,0])

[3 4 1 6 3 1]
[3 6 3 6 2]
[3 5 3 3]

[[3 5 3 3]
 [6 1 3 6]
 [3 1 1 3]
 [6 3 1 4]
 [2 6 4 1]]

(5, 4)
3


In [17]:
array_2 = np.random.randint(1,7, size = (6,5,5,5))
print(array_2)
array_2[0:1,0:1,0:2,:2] # so this is (index,index,row,coloum)

[[[[1 4 6 3 4]
   [1 3 1 4 6]
   [6 6 2 3 6]
   [1 2 2 6 6]
   [2 3 1 6 6]]

  [[3 2 1 6 6]
   [1 6 5 5 3]
   [3 1 6 2 2]
   [2 3 2 3 3]
   [2 6 4 3 6]]

  [[6 2 6 5 1]
   [2 3 1 1 6]
   [1 3 3 5 4]
   [5 6 6 3 4]
   [5 1 5 1 6]]

  [[3 1 4 4 1]
   [5 6 3 5 6]
   [2 1 6 5 6]
   [4 1 2 6 1]
   [2 1 6 6 3]]

  [[6 4 1 1 1]
   [2 3 3 4 3]
   [5 2 1 3 4]
   [3 6 4 6 3]
   [3 4 2 3 2]]]


 [[[6 5 1 6 5]
   [5 2 4 1 1]
   [1 6 1 3 2]
   [4 5 1 3 1]
   [4 5 5 2 3]]

  [[6 6 4 2 2]
   [2 2 6 3 6]
   [6 4 3 5 6]
   [5 3 2 2 3]
   [1 4 3 4 3]]

  [[4 3 1 4 4]
   [3 2 4 4 1]
   [1 1 2 1 1]
   [3 4 5 6 1]
   [2 5 5 6 1]]

  [[2 1 3 3 1]
   [4 4 3 6 3]
   [2 4 5 5 1]
   [3 4 2 2 3]
   [4 3 3 4 2]]

  [[1 2 4 6 2]
   [1 2 3 2 6]
   [4 4 1 5 6]
   [6 5 1 4 1]
   [5 2 6 4 1]]]


 [[[4 1 2 6 2]
   [1 6 4 2 3]
   [1 5 5 4 6]
   [4 5 5 4 4]
   [4 4 6 1 2]]

  [[1 3 5 2 4]
   [3 6 5 2 4]
   [1 3 4 1 2]
   [2 4 5 2 2]
   [6 1 3 2 3]]

  [[3 6 2 3 2]
   [1 3 6 1 1]
   [2 3 2 5 3]
   [4 4 5 3 6]
   [5 5 1 1 

array([[[[1, 4],
         [1, 3]]]])