# Numpy operations 

In [1]:
import numpy as np

In [3]:
np.random.seed()
matrix=np.random.randint(11,49, size = (2,4,4))

In [4]:
matrix

array([[[46, 11, 12, 28],
        [15, 40, 31, 34],
        [48, 15, 48, 32],
        [39, 43, 38, 19]],

       [[36, 17, 18, 42],
        [48, 23, 47, 36],
        [30, 34, 43, 31],
        [40, 14, 20, 24]]])

In [5]:
matrix.transpose()

array([[[46, 36],
        [15, 48],
        [48, 30],
        [39, 40]],

       [[11, 17],
        [40, 23],
        [15, 34],
        [43, 14]],

       [[12, 18],
        [31, 47],
        [48, 43],
        [38, 20]],

       [[28, 42],
        [34, 36],
        [32, 31],
        [19, 24]]])

In [6]:
matrix.reshape((8,4))

array([[46, 11, 12, 28],
       [15, 40, 31, 34],
       [48, 15, 48, 32],
       [39, 43, 38, 19],
       [36, 17, 18, 42],
       [48, 23, 47, 36],
       [30, 34, 43, 31],
       [40, 14, 20, 24]])

In [7]:
np.reshape(matrix,(4,8))

array([[46, 11, 12, 28, 15, 40, 31, 34],
       [48, 15, 48, 32, 39, 43, 38, 19],
       [36, 17, 18, 42, 48, 23, 47, 36],
       [30, 34, 43, 31, 40, 14, 20, 24]])

In [9]:
matrix.shape = (4,2,4)
matrix

array([[[46, 11, 12, 28],
        [15, 40, 31, 34]],

       [[48, 15, 48, 32],
        [39, 43, 38, 19]],

       [[36, 17, 18, 42],
        [48, 23, 47, 36]],

       [[30, 34, 43, 31],
        [40, 14, 20, 24]]])

In [11]:
matrix.reshape((-1,4)) # if you don't know how many rows you need you can do this 

array([[46, 11, 12, 28],
       [15, 40, 31, 34],
       [48, 15, 48, 32],
       [39, 43, 38, 19],
       [36, 17, 18, 42],
       [48, 23, 47, 36],
       [30, 34, 43, 31],
       [40, 14, 20, 24]])

In [14]:
mat1 = np.array(np.random.randint(1,100, size =(6,6)))
mat1

array([[96, 19,  6, 67, 97, 29],
       [30, 43, 53,  4, 16, 85],
       [30, 62, 35, 39, 77, 38],
       [91, 89, 43, 68, 75, 57],
       [62, 61, 23, 30, 44, 72],
       [65, 13, 46, 97, 95, 65]])

In [16]:
np.reshape(mat1,(-1,4))

array([[96, 19,  6, 67],
       [97, 29, 30, 43],
       [53,  4, 16, 85],
       [30, 62, 35, 39],
       [77, 38, 91, 89],
       [43, 68, 75, 57],
       [62, 61, 23, 30],
       [44, 72, 65, 13],
       [46, 97, 95, 65]])

So the reshape can take negative values and basically those negative value means the you hand not made up you mind about how many rows/ columns you want 

In [17]:
mat1.reshape((4,-1)) # 

array([[96, 19,  6, 67, 97, 29, 30, 43, 53],
       [ 4, 16, 85, 30, 62, 35, 39, 77, 38],
       [91, 89, 43, 68, 75, 57, 62, 61, 23],
       [30, 44, 72, 65, 13, 46, 97, 95, 65]])

# It's either np.method or array.method try both way in most cases both of them work but not with the array.flatten()

In [20]:
mat1.reshape(-1,-1,4) # takes only one unknown

ValueError: can only specify one unknown dimension

In [21]:
np.reshape(mat1,(-1,4,3))

array([[[96, 19,  6],
        [67, 97, 29],
        [30, 43, 53],
        [ 4, 16, 85]],

       [[30, 62, 35],
        [39, 77, 38],
        [91, 89, 43],
        [68, 75, 57]],

       [[62, 61, 23],
        [30, 44, 72],
        [65, 13, 46],
        [97, 95, 65]]])

In [24]:
np.reshape(mat1,(-1,))

array([96, 19,  6, 67, 97, 29, 30, 43, 53,  4, 16, 85, 30, 62, 35, 39, 77,
       38, 91, 89, 43, 68, 75, 57, 62, 61, 23, 30, 44, 72, 65, 13, 46, 97,
       95, 65])

In [25]:
np.reshape(mat1,(1,-1))

array([[96, 19,  6, 67, 97, 29, 30, 43, 53,  4, 16, 85, 30, 62, 35, 39,
        77, 38, 91, 89, 43, 68, 75, 57, 62, 61, 23, 30, 44, 72, 65, 13,
        46, 97, 95, 65]])

In [26]:
np.reshape(mat1,(-1,1))

array([[96],
       [19],
       [ 6],
       [67],
       [97],
       [29],
       [30],
       [43],
       [53],
       [ 4],
       [16],
       [85],
       [30],
       [62],
       [35],
       [39],
       [77],
       [38],
       [91],
       [89],
       [43],
       [68],
       [75],
       [57],
       [62],
       [61],
       [23],
       [30],
       [44],
       [72],
       [65],
       [13],
       [46],
       [97],
       [95],
       [65]])

In [28]:
mat2 = np.array(np.random.randint(1,100, size = (4,4)))
mat2

array([[88, 13, 61, 10],
       [68, 40, 33, 32],
       [ 7, 17, 59, 46],
       [82, 84, 92, 65]])

In resize when you are resizeing the array it does not created new elements it just choose same elemnts from the original list starting from the a[0,0] and moves so on

In [29]:
np.resize(mat2,(2,4,3)) 

array([[[88, 13, 61],
        [10, 68, 40],
        [33, 32,  7],
        [17, 59, 46]],

       [[82, 84, 92],
        [65, 88, 13],
        [61, 10, 68],
        [40, 33, 32]]])

In [33]:
np.random.seed()
mat3=np.random.randint(1,99,size = (5,5))
mat3

array([[ 8, 76, 19, 65, 34],
       [20, 61, 87, 10, 17],
       [77, 72, 40, 83,  5],
       [65, 24, 59, 26, 13],
       [35, 15, 56, 35, 63]])

In [35]:
s = (3,3,4)
mat3.resize(s)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [43]:
matrix  = np.array([[ 8, 76, 19, 65, 34],
       [20, 61, 87, 10, 17],
       [77, 72, 40, 83,  5],
       [65, 24, 59, 26, 13],
       [35, 15, 56, 35, 63]])
matrix

array([[ 8, 76, 19, 65, 34],
       [20, 61, 87, 10, 17],
       [77, 72, 40, 83,  5],
       [65, 24, 59, 26, 13],
       [35, 15, 56, 35, 63]])

In [44]:
matrix.resize((3,3,4))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [39]:
matrix.flatten()

array([ 8, 76, 19, 65, 34, 20, 61, 87, 10, 17, 77, 72, 40, 83,  5, 65, 24,
       59, 26, 13, 35, 15, 56, 35, 63])

In [40]:
np.flatten(matrix)

AttributeError: module 'numpy' has no attribute 'flatten'

In [47]:
matrix

array([[ 8, 76, 19, 65, 34],
       [20, 61, 87, 10, 17],
       [77, 72, 40, 83,  5],
       [65, 24, 59, 26, 13],
       [35, 15, 56, 35, 63]])

In [46]:
matrix.flatten('C') # column wise flattening 

array([ 8, 76, 19, 65, 34, 20, 61, 87, 10, 17, 77, 72, 40, 83,  5, 65, 24,
       59, 26, 13, 35, 15, 56, 35, 63])

In [49]:
matrix.flatten('F') # row wise flattening 

array([ 8, 20, 77, 65, 35, 76, 61, 72, 24, 15, 19, 87, 40, 59, 56, 65, 10,
       83, 26, 35, 34, 17,  5, 13, 63])

In [57]:
# 3D Array
random_3d_array = np.array(np.random.randint(10,45,(3,2,4)))
print(f"The defined array is \n{random_3d_array}")
print(f" \n The shape of the array is {random_3d_array.shape}")

The defined array is 
[[[33 34 32 37]
  [37 11 40 37]]

 [[14 14 27 23]
  [20 40 12 31]]

 [[37 42 13 42]
  [27 33 36 37]]]
 
 The shape of the array is (3, 2, 4)


In [59]:
transposed = np.transpose(random_3d_array)
print(transposed)
print(transposed.shape)
print(random_3d_array.shape)

[[[33 14 37]
  [37 20 27]]

 [[34 14 42]
  [11 40 33]]

 [[32 27 13]
  [40 12 36]]

 [[37 23 42]
  [37 31 37]]]
(4, 2, 3)
(3, 2, 4)


In [61]:
np.random.seed()
mat1 = np.array(np.random.randint(1,50,(3,3,3)))
mat1

array([[[38, 39,  1],
        [ 8, 44, 41],
        [32, 23, 16]],

       [[ 5, 26, 48],
        [32, 34, 11],
        [24, 16, 47]],

       [[41, 17, 39],
        [49,  2, 44],
        [20, 20,  9]]])

# np.insert()

In [62]:
np.insert(mat1,1,-99,axis = 0)

array([[[ 38,  39,   1],
        [  8,  44,  41],
        [ 32,  23,  16]],

       [[-99, -99, -99],
        [-99, -99, -99],
        [-99, -99, -99]],

       [[  5,  26,  48],
        [ 32,  34,  11],
        [ 24,  16,  47]],

       [[ 41,  17,  39],
        [ 49,   2,  44],
        [ 20,  20,   9]]])

In [63]:
np.insert(mat1,1,-99,axis = 1)

array([[[ 38,  39,   1],
        [-99, -99, -99],
        [  8,  44,  41],
        [ 32,  23,  16]],

       [[  5,  26,  48],
        [-99, -99, -99],
        [ 32,  34,  11],
        [ 24,  16,  47]],

       [[ 41,  17,  39],
        [-99, -99, -99],
        [ 49,   2,  44],
        [ 20,  20,   9]]])

In [64]:
np.insert(mat1,1,99,axis = 2)

array([[[38, 99, 39,  1],
        [ 8, 99, 44, 41],
        [32, 99, 23, 16]],

       [[ 5, 99, 26, 48],
        [32, 99, 34, 11],
        [24, 99, 16, 47]],

       [[41, 99, 17, 39],
        [49, 99,  2, 44],
        [20, 99, 20,  9]]])

**So in the np.insert(array,index, value,axis) axis here corrospond to something different, it kind of relates more to the shape of the matrix rather than the conventional idea of axis,lets understand this, we have a 3d matrix whose shape, lets say is (3,4,2) where 3 is the no. of 2d array( no. of 2 matrix), 4 is the no. of row in each matrix and 2 is the no. of column in each matrix, Now when we talk about the np.insert, the axis and shape are corelated,usually we are acoustumed with the concept of having only 2 axis i.e row or col but in this method the  no. of axis is equal to no. of elements in the array.shape so axis = 0 means that at what layer you want the new array  to be added, axis = 1 means at what row (each row in the composition) you want the new values to be added  and  axis = 2 means at what column in the matrix(each column in the compostion) you want the values  to be added we can futher expand this concpet ot 4d,5d,6d and so on...  which will have axis = 4, 5, 6 and so on.....**

In [65]:
mat1

array([[[38, 39,  1],
        [ 8, 44, 41],
        [32, 23, 16]],

       [[ 5, 26, 48],
        [32, 34, 11],
        [24, 16, 47]],

       [[41, 17, 39],
        [49,  2, 44],
        [20, 20,  9]]])

In [68]:
np.insert(mat1,0,[1,2,3],axis = 2)

array([[[ 1, 38, 39,  1],
        [ 2,  8, 44, 41],
        [ 3, 32, 23, 16]],

       [[ 1,  5, 26, 48],
        [ 2, 32, 34, 11],
        [ 3, 24, 16, 47]],

       [[ 1, 41, 17, 39],
        [ 2, 49,  2, 44],
        [ 3, 20, 20,  9]]])

In [73]:
np.insert(mat1,2,[1,2,3],axis = 1)

array([[[38, 39,  1],
        [ 8, 44, 41],
        [ 1,  2,  3],
        [32, 23, 16]],

       [[ 5, 26, 48],
        [32, 34, 11],
        [ 1,  2,  3],
        [24, 16, 47]],

       [[41, 17, 39],
        [49,  2, 44],
        [ 1,  2,  3],
        [20, 20,  9]]])

In [74]:
np.insert(mat1,2,[1,2],axis = 1)

ValueError: could not broadcast input array from shape (1,1,2) into shape (3,1,3)

In [78]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [1]:
import numpy as np

In [31]:
array1 = np.random.randint(1,100, size = (4,5))

In [32]:
array1 

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [33]:
np.transpose(array1)

array([[56, 21,  9, 21],
       [19, 38, 16, 49],
       [95, 28, 55, 11],
       [38, 25, 54, 90],
       [66, 77, 50, 55]])

In [34]:
array1

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [35]:
array1.transpose()

array([[56, 21,  9, 21],
       [19, 38, 16, 49],
       [95, 28, 55, 11],
       [38, 25, 54, 90],
       [66, 77, 50, 55]])

In [36]:
array1

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [37]:
array2 = np.array(np.random.randint(1,100,size=(2,3,4)))

In [38]:
array2

array([[[13, 80, 56, 43],
        [28, 43, 94,  3],
        [92, 34, 77, 22]],

       [[66, 40, 54, 52],
        [11, 57, 22, 95],
        [27, 84, 43, 26]]])

In [39]:
array2.transpose()

array([[[13, 66],
        [28, 11],
        [92, 27]],

       [[80, 40],
        [43, 57],
        [34, 84]],

       [[56, 54],
        [94, 22],
        [77, 43]],

       [[43, 52],
        [ 3, 95],
        [22, 26]]])

In [40]:
np.reshape(array1,(5,4))

array([[56, 19, 95, 38],
       [66, 21, 38, 28],
       [25, 77,  9, 16],
       [55, 54, 50, 21],
       [49, 11, 90, 55]])

In [41]:
array1

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [42]:
array1.reshape(5,4)

array([[56, 19, 95, 38],
       [66, 21, 38, 28],
       [25, 77,  9, 16],
       [55, 54, 50, 21],
       [49, 11, 90, 55]])

In [43]:
array1

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [44]:
array2.reshape(6,4)

array([[13, 80, 56, 43],
       [28, 43, 94,  3],
       [92, 34, 77, 22],
       [66, 40, 54, 52],
       [11, 57, 22, 95],
       [27, 84, 43, 26]])

In [47]:
np.reshape(array2,(2,4,3))

array([[[13, 80, 56],
        [43, 28, 43],
        [94,  3, 92],
        [34, 77, 22]],

       [[66, 40, 54],
        [52, 11, 57],
        [22, 95, 27],
        [84, 43, 26]]])

In [48]:
array1

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [49]:
np.resize(array1,(5,5))

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55],
       [56, 19, 95, 38, 66]])

In [56]:
#array1.resize(6,5)
np.resize(array1,(4,5))

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [57]:
array1.flatten()

array([56, 19, 95, 38, 66, 21, 38, 28, 25, 77,  9, 16, 55, 54, 50, 21, 49,
       11, 90, 55])

In [58]:
array1

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [59]:
np.flatten(array1)

AttributeError: module 'numpy' has no attribute 'flatten'

In [60]:
np.insert(array1,1,99,axis = 0)

array([[56, 19, 95, 38, 66],
       [99, 99, 99, 99, 99],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [61]:
array0 = np.arange(1,15)
array0

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
np.insert(array0,1,99,axis = 0)

array([ 1, 99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
array2

array([[[13, 80, 56, 43],
        [28, 43, 94,  3],
        [92, 34, 77, 22]],

       [[66, 40, 54, 52],
        [11, 57, 22, 95],
        [27, 84, 43, 26]]])

In [65]:
np.insert(array2,1,[[-1,-2,-3,-4],[-1,-2,-3,-4],[-1,-2,-3,-4]], axis = 0)

array([[[13, 80, 56, 43],
        [28, 43, 94,  3],
        [92, 34, 77, 22]],

       [[-1, -2, -3, -4],
        [-1, -2, -3, -4],
        [-1, -2, -3, -4]],

       [[66, 40, 54, 52],
        [11, 57, 22, 95],
        [27, 84, 43, 26]]])

In [66]:
np.insert(array2,1,99,axis = 0)

array([[[13, 80, 56, 43],
        [28, 43, 94,  3],
        [92, 34, 77, 22]],

       [[99, 99, 99, 99],
        [99, 99, 99, 99],
        [99, 99, 99, 99]],

       [[66, 40, 54, 52],
        [11, 57, 22, 95],
        [27, 84, 43, 26]]])

In [67]:
np.insert(array2,2,[1,2,3],axis = 2)

array([[[13, 80,  1, 56, 43],
        [28, 43,  2, 94,  3],
        [92, 34,  3, 77, 22]],

       [[66, 40,  1, 54, 52],
        [11, 57,  2, 22, 95],
        [27, 84,  3, 43, 26]]])

In [68]:
np.insert(array2,2,[6,5,4,5],axis = 1)

array([[[13, 80, 56, 43],
        [28, 43, 94,  3],
        [ 6,  5,  4,  5],
        [92, 34, 77, 22]],

       [[66, 40, 54, 52],
        [11, 57, 22, 95],
        [ 6,  5,  4,  5],
        [27, 84, 43, 26]]])

In [74]:
array1

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55]])

In [75]:
a = np.array([[1,2,3,4,5]])
a

array([[1, 2, 3, 4, 5]])

In [80]:
np.append(array1,a,axis = 0)

array([[56, 19, 95, 38, 66],
       [21, 38, 28, 25, 77],
       [ 9, 16, 55, 54, 50],
       [21, 49, 11, 90, 55],
       [ 1,  2,  3,  4,  5]])

In [81]:
a = np.array(np.random.randint(1,100,size= (3,4)))

In [95]:
a

array([[23, 29, 89, 71],
       [96, 72, 14, 92],
       [21, 32, 59,  2]])

In [97]:
b = np.array(np.random.randint(1,100,size=(1,4)))

In [98]:
b

array([[54, 59, 37, 80]])

In [100]:
b.shape,b.ndim

((1, 4), 2)

In [91]:
np.append(a,b, axis = 0)

array([[23, 29, 89, 71],
       [96, 72, 14, 92],
       [21, 32, 59,  2],
       [39, 63,  2, 96]])

In [103]:
np.append(a,b,axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [105]:
x = np.random.randint(1,100,size = (2,3))
y = np.random.randint(1,100,size = (2,3))
print(x)
print(y)

[[ 8 14 96]
 [ 1 97 23]]
[[15 92 22]
 [43 64 97]]


In [106]:
np.append(x,y,axis = 0)

array([[ 8, 14, 96],
       [ 1, 97, 23],
       [15, 92, 22],
       [43, 64, 97]])

In [107]:
np.append(x,y,axis = 1)

array([[ 8, 14, 96, 15, 92, 22],
       [ 1, 97, 23, 43, 64, 97]])

In [108]:
x.append(y)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [110]:
np.append(x,50)

array([ 8, 14, 96,  1, 97, 23, 50])

In [113]:
np.append(y,x,axis = 1)

array([[15, 92, 22,  8, 14, 96],
       [43, 64, 97,  1, 97, 23]])

In [117]:
array = np.array(np.random.randint(1,100,size = (5,5)))
array.size

25

In [118]:
np.delete(array,1)

array([53,  4, 91, 11, 38, 80, 15, 91,  6, 27, 66,  7, 23, 41, 67, 27, 76,
       51, 14, 92, 25, 28, 38, 69])

In [119]:
np.delete(array,1,axis = 0)

array([[53, 63,  4, 91, 11],
       [27, 66,  7, 23, 41],
       [67, 27, 76, 51, 14],
       [92, 25, 28, 38, 69]])

In [120]:
np.delete(array,1,axis = 1)

array([[53,  4, 91, 11],
       [38, 15, 91,  6],
       [27,  7, 23, 41],
       [67, 76, 51, 14],
       [92, 28, 38, 69]])

In [122]:
array.flatten()

array([53, 63,  4, 91, 11, 38, 80, 15, 91,  6, 27, 66,  7, 23, 41, 67, 27,
       76, 51, 14, 92, 25, 28, 38, 69])

In [123]:
array.flatten('F')

array([53, 38, 27, 67, 92, 63, 80, 66, 27, 25,  4, 15,  7, 76, 28, 91, 91,
       23, 51, 38, 11,  6, 41, 14, 69])

In [124]:
array.flatten('C')

array([53, 63,  4, 91, 11, 38, 80, 15, 91,  6, 27, 66,  7, 23, 41, 67, 27,
       76, 51, 14, 92, 25, 28, 38, 69])

In [129]:
np.unique(array)

array([ 4,  6,  7, 11, 14, 15, 23, 25, 27, 28, 38, 41, 51, 53, 63, 66, 67,
       69, 76, 80, 91, 92])

In [130]:
np.unique(array,return_counts = True)

(array([ 4,  6,  7, 11, 14, 15, 23, 25, 27, 28, 38, 41, 51, 53, 63, 66, 67,
        69, 76, 80, 91, 92]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
       dtype=int64))

In [131]:
np.unique(array,return_counts = True,return_index = True )

(array([ 4,  6,  7, 11, 14, 15, 23, 25, 27, 28, 38, 41, 51, 53, 63, 66, 67,
        69, 76, 80, 91, 92]),
 array([ 2,  9, 12,  4, 19,  7, 13, 21, 10, 22,  5, 14, 18,  0,  1, 11, 15,
        24, 17,  6,  3, 20], dtype=int64),
 array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
       dtype=int64))

## the return_index returns the index of flattened array 

In [132]:
# Python program to inverse
# a matrix using numpy

# Import required package
import numpy as np

# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
			[4, -2, 5],
			[2, 8, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(A))


[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [133]:
array 

array([[53, 63,  4, 91, 11],
       [38, 80, 15, 91,  6],
       [27, 66,  7, 23, 41],
       [67, 27, 76, 51, 14],
       [92, 25, 28, 38, 69]])

In [139]:
np.sum(array,3)

AxisError: axis 3 is out of bounds for array of dimension 2

In [142]:
np.sum(array,0)

array([277, 261, 130, 294, 141])

In [143]:
array

array([[53, 63,  4, 91, 11],
       [38, 80, 15, 91,  6],
       [27, 66,  7, 23, 41],
       [67, 27, 76, 51, 14],
       [92, 25, 28, 38, 69]])

In [145]:
np.sum(array[:,2],axis = 0)

130

In [147]:
np.sum(array,axis = 0)

array([277, 261, 130, 294, 141])

In [148]:
np.average(array,)

array([44.4, 46. , 32.8, 47. , 50.4])

In [3]:
array1 = np.array(np.random.randint(1,100,size = (3,3)))
array2 = np.array(np.random.randint(1,100,size = (3,3)))

In [4]:
print(array1)
print(array2)

[[73  8 49]
 [25 28 38]
 [83 65 71]]
[[74 83 87]
 [81 59 22]
 [22 72 33]]


In [6]:
np.append(array1,array2,axis = 1)

array([[73,  8, 49, 74, 83, 87],
       [25, 28, 38, 81, 59, 22],
       [83, 65, 71, 22, 72, 33]])

In [12]:
np.unique(array1,1)

(array([ 8, 25, 28, 38, 49, 65, 71, 73, 83]),
 array([1, 3, 4, 5, 2, 7, 8, 0, 6], dtype=int64))

In [14]:
array1

array([[73,  8, 49],
       [25, 28, 38],
       [83, 65, 71]])

In [15]:
array2

array([[74, 83, 87],
       [81, 59, 22],
       [22, 72, 33]])

In [21]:
array3 = array1.view()

In [23]:
array3[0,0] = 999

In [24]:
array3

array([[999,   8,  49],
       [ 25,  28,  38],
       [ 83,  65,  71]])

In [25]:
array1

array([[999,   8,  49],
       [ 25,  28,  38],
       [ 83,  65,  71]])

In [26]:
array4 = array2.copy()

In [27]:
array2,array4

(array([[74, 83, 87],
        [81, 59, 22],
        [22, 72, 33]]),
 array([[74, 83, 87],
        [81, 59, 22],
        [22, 72, 33]]))

In [28]:
array4[0,0] = 100000

In [29]:
array4

array([[100000,     83,     87],
       [    81,     59,     22],
       [    22,     72,     33]])

In [30]:
array2

array([[74, 83, 87],
       [81, 59, 22],
       [22, 72, 33]])

In [31]:
array1

array([[999,   8,  49],
       [ 25,  28,  38],
       [ 83,  65,  71]])

In [43]:
a=np.array([1,2,3]) # try undertanding this with the excel drag anology 

In [44]:
array1 + a

array([[1000,   10,   52],
       [  26,   30,   41],
       [  84,   67,   74]])

# if you have unique elements than it becomes easy for the interpreter to broadcast but it it has non unique elements then it gets confused , the uniqueness is both when it comes to column and rows

In [46]:
array1

array([[999,   8,  49],
       [ 25,  28,  38],
       [ 83,  65,  71]])

In [47]:
np.sum(array1,axis = 1)

array([1056,   91,  219])

In [48]:
np.sum(array1,axis = 0)

array([1107,  101,  158])

In [49]:
np.max(array1)

999

In [50]:
np.max(array1,axis = 0)

array([999,  65,  71])

In [53]:
np.max(array1,axis = 1)

array([999,  38,  83])