# How to take user input 

In [4]:
x = []
y = []
for _ in range(int(input())): # 
    name = input('Please enter name: ')
    score = int(input('Please enter marks: '))
    x.append(name)
    y.append(score)
print(x)
print(y)
# We will document this tomorrow 

1
Please enter name: d
Please enter marks: 43
['d']
[43]


In [1]:
 for _ in range(int(input())):
        name = input()
        score = float(input())

2
sww
as


ValueError: could not convert string to float: 'as'

# lets created a nested list 


In [12]:
x = ['a','b','c','d']
y = [1,2,3,4]
z = []
for i in range(len(x)):
    z.append([])
#     print(z)
    for j in range(1):
        z[i].append(x[i])
#         print(z)
    z[i].append(y[i])
print(z)    

[['a', 1], ['b', 2], ['c', 3], ['d', 4]]


In [5]:
x = [a,b,c,d]
y = [1,2,3,4]
z = []
for i in range(len(x)):
    z.append([])
    print(z)
#     for j in range(1):
#         z[i].append(x[i])
#     x[i].append(y[i])
# print(z)    

NameError: name 'a' is not defined

In [20]:
x = ['Deepu','Amit','Chitu','Vikas','Pawan']
y = [34,23,43,45,32]
z = []
for i in range(len(x)):
    z.append([])
    for j in range(1):
        z[i].append(x[i])
        z[i].append(y[i])
print(z)        

[['Deepu', 34], ['Amit', 23], ['Chitu', 43], ['Vikas', 45], ['Pawan', 32]]


**First write the logic how will you go about this problem**

You will create an empty list 

Then you will create empty list within empty list 

Then using index you will append the element of x list into the first empty list in the z using index

Then again append y elment in the z using index

In [ ]:
list_x = ['Deepu','Rahul', 'Vikas','Bhanu']
list_y = [23,32,34,43,]
list_z = []

In [27]:
nested = [['Deepu', 34], ['Amit', 23], ['Chitu', 43], ['Vikas', 45], ['Pawan', 32]]
for i in nested:
    print(i[1])

34
23
43
45
32


In [2]:
dicty = {'deepu':34,'rahul':43,'Sanjay':43}

In [4]:
dicty[34]

KeyError: 34

In [10]:
dicty = {1:2,2:3,3:5}
dicty[1]

2

In [34]:
listy = [['Deepu',23],['Sanjay',43],['Rahul',43]]
emp = []
for i in listy:
    if i[1] == 43:
        emp.append(i[0])
sorted(emp,reverse=False)
print(emp)

['Sanjay', 'Rahul']


In [2]:
x_name = []
y_score = []
for _ in range(int(input())):
    name = input('Please enter name of the student: ')
    score = float(input('Please enter the score of the student: '))
    x_name.append(name)
    y_score.append(score)
# print(x_name,y_score)    

# We are creating a nested list 
nested = []
for i in range(len(x_name)):
    nested.append([])
    for j in range(1):
        nested[i].append(x_name[i])
        nested[i].append(y_score[i])
print(nested) 

# finding the smallest score 
for i in range(1,len(y_score)):
    value = y_score[i]
    j = i
    while j > 0 and y_score[j-1] > value:
        y_score[j] = y_score[j-1]
        j -= 1
    y_score[j] = value 
print(y_score)

# reduce the frequency of the score to just one 
dicty = {}
for s in y_score:
    if s in dicty:
        dicty[s] += 1
    else:
        dicty[s] = 1
non_repeating = list(dicty.keys())        
    

# print the name of the 2nd lowest
result = []
for nest in nested:
    if nest[1] == non_repeating[1]:
        result.append(nest[0])

arranged = sorted(result, reverse = False)        
for item in arranged:
    print(item)

4
Please enter name of the student: Rachel
Please enter the score of the student: -50
Please enter name of the student: Mawer
Please enter the score of the student: -50
Please enter name of the student: Sheen
Please enter the score of the student: -50
Please enter name of the student: Shaheen
Please enter the score of the student: 51
[['Rachel', -50.0], ['Mawer', -50.0], ['Sheen', -50.0], ['Shaheen', 51.0]]
[-50.0, -50.0, -50.0, 51.0]
Shaheen


In [ ]:
4
Please enter name of the student: Rachel
Please enter the score of the student: -50
Please enter name of the student: Mawer
Please enter the score of the student: -50
Please enter name of the student: Sheen
Please enter the score of the student: -50
Please enter name of the student: Shaheen
Please enter the score of the student: 51


In [43]:
y_score = [34.3,54.23,43.22]
for i in range(1,len(y_score)):
    value = y_score[i]
    j = i
    while j > 0 and y_score[j-1] > value:
        y_score[j] = y_score[j-1]
        j -= 1
    y_score[j] = value 
print(y_score)    

[34.3, 43.22, 54.23]


In [46]:
nes=[['deepu ', 43.0], ['sanjay', 45.0], ['rahul', 55.0]]
for i in nes:
    if i[1] == 43.0:
        print(i[0])

deepu 


In [15]:
sortit = {}
lis = [-50.0, -50.0, -50.0, 51.0]
for i in lis:
    if i in sortit:
        sortit[i] += 1
        
    else:
        sortit[i] = 1
print(sortit)  
print(list(sortit.keys()))


{-50.0: 3, 51.0: 1}
[-50.0, 51.0]


In [1]:
lis = [1,1,1,2,2,3,4,4,3,5,6]
dicty = {}
for i in lis:
    if i in dicty:
        dicty[i] = dicty[i] + 1
    else:
        dicty[i] = 1
print(dicty)        

{1: 3, 2: 2, 3: 2, 4: 2, 5: 1, 6: 1}


# Finding the percentage 

In [24]:
lis = {'Krishna': [67.0, 68.0, 69.0], 'Arjun': [70.0, 98.0, 63.0], 'Malika': [52.0, 56.0, 60.0]}
val = input('Enter the name of the student whose average marks you want to find: ')
y = sum(lis[val])/len(lis[val])
result = round(y,3)
print(result)

Enter the name of the student whose average marks you want to find: Malika
56.0


In [18]:
z = [1,2,3,4]
print(sum(z))

10


In [28]:
y = 98.3
result = round(y,3)
print(result*1.00)

98.3


In [53]:
y = 69.0
print("%.2f" % y) # 
print("%.4f" % y)


69.00
69.0000


In [54]:
floatNumber = 1.9876

print("%f" % floatNumber) # by default it takes up to 6 places from the right of the point 
# 1.987600

1.987600


In [55]:
lis = {'Krishna': [67.0, 68.0, 69.0], 'Arjun': [70.0, 98.0, 63.0], 'Malika': [52.0, 56.0, 60.0]}


In [1]:
lis = [1,2,3,4,5]
value = 0
for i in lis:
    value = value + i
print(value)    

15


In [1]:
lis = []
lis.append(5)
print(lis)

[5]


In [3]:
if __name__ == '__main__':
    N = int(input())
    
    

3


In [7]:
lis = []
lis.append(5)
lis.append(10)
lis.insert(0,6)
print(lis)


[6, 5, 10]


In [9]:
val = int(input('Please enter the no. you want in the first place: '))
lis = [1,2,3,8,9]
lisy = []
lisy.append(val)
for i in range(len(lis)):
    lisy.append(lis[i])
print(lisy)    
    
    

Please enter the no. you want in the first place: 789
[789, 1, 2, 3]


In [16]:
if __name__ == '__main__':
    N = int(input('Enter the times you want to use this feature : '))
    for i in range(N):
        cmd = input()
        if cmd[i] == insert:
            
            
        
    
        
        

IndentationError: expected an indented block (403097700.py, line 10)

In [6]:
val = int(input('Enter the times you want to use this feature'))
for i in range(val):
    name = input()
    print('You have entered',name)

Enter the times you want to use this feature3
deepu 
You have entered deepu 
rahul 
You have entered rahul 
sanjay 
You have entered sanjay 


In [2]:
val = int(input())
for i in range(val):
    name = input()
    print('You have entered',name)

3
deepu
You have entered deepu
sanjay
You have entered sanjay
rahul
You have entered rahul


In [ ]:
val = int(input('Enter how many time you want to run this algo: '))
for i in range

In [8]:
y = []
for _ in range(int(input())):
    name = input()
    y.append(name)
print(y)    

3
deepu 
sanjay 
rahul 
['deepu ', 'sanjay ', 'rahul ']


In [9]:
# does the same work as above code 
y = []
for i in range(int(input())):
    name = input()
    y.append(name)
print(y)  

3
deepu 
ajay 
sanjay 
['deepu ', 'ajay ', 'sanjay ']


# Nested list question what will you learn here how to take user define input which is both in string and int form 
# Use the slicing knowledge and datatype conversion function

In [49]:
val = int(input('Enter how many times you want to run this algo: '))
lis = []
for i in range(val):
    operation = input('Enter command: ').strip()
    if operation[:6] == 'insert':
       lis.insert(int(operation[7]),int(operation[9:]))
    elif operation == 'print':
        print(lis)
    elif operation[:6] == 'remove':
        lis.remove(int(operation[7:]))
    elif operation[0:6] == 'append':
        lis.append(int(operation[7:]))
    elif operation == 'sort':
        lis.sort()
    elif operation == 'pop':
        lis.pop()
    elif operation == 'reverse':
        lis.reverse()
            

Enter how many times you want to run this algo: 12
Enter command: insert 0 5
Enter command: insert 1 10
Enter command: insert 0 6
Enter command: print
[6, 5, 10]
Enter command: remove 6
Enter command: append 9
Enter command: append 1
Enter command: sort
Enter command: print
[1, 5, 9, 10]
Enter command: pop
Enter command: reverse
Enter command: print
[9, 5, 1]


In [14]:
lis = []
lis.insert(0,5)
print(lis)

[5]


In [2]:
val = int(input())
if val == 2:
    print('yes my lady')

2
yes my lady


In [16]:
val = str(input('please enter no. '))
if val[1] == 'e':
    print('hey')


please enter no.  e
hey


In [14]:
lis = 'deepu'
print(lis[1])

e


In [21]:
val = input().strip()
print(val[0])

       Deepu
D


In [38]:
l = []
f = 'insert 0 5'
print(type(int(f[7])))
print(f[9])

<class 'int'>
5


In [48]:
listy = [3,2,1,45]
listy.sort()
print(listy)

[1, 2, 3, 45]


# Tuple Hash

Hash function basically creates a hash value of immutable objects like tupe and int

# conveting the letter from big to small and viceversa

In [21]:
string = 'Pythonist 2'
y = ''
for letter in string:
    if letter == letter.upper():
        small = letter.lower()
#         print(small)
        y = y + small # reassigning the value as there is no append function in string why because its imutable 
    else:
        big = letter.upper()
#         print(big)
        y = y + big # reassigning the y 
print(y) 

pYTHONIST 2


In [2]:
x = 'deepu'
x.upper()

'DEEPU'

In [7]:
x = '2'
y = '3'
x+y

'23'

In [19]:
string = str(input())
y = ''
for letter in string:
    if letter == letter.upper():
        small = letter.lower()
#         print(small)
        y = y + small # reassigning the value as there is no append function in string why because its imutable 
    else:
        big = letter.upper()
#         print(big)
        y = y + big # reassigning the y 
print(y) 

deepu
DEEPU


In [20]:
test = 'Deepu'
swap_case(test)

NameError: name 'swap_case' is not defined

In [22]:
s = 'Pythonist 2'
y = ''
for letter in s:
    if letter == letter.upper():
        small = letter.lower()
#         print(small)
        y = y + small # reassigning the value as there is no append function in string why because its imutable 
    else:
        big = letter.upper()
#         print(big)
        y = y + big # reassigning the y 
print(y) 

pYTHONIST 2


In [26]:
def swap_case(s):
    y = ''
    for letter in s:
        if letter == letter.upper():
            small = letter.lower()
#           print(small)
            y = y + small # reassigning the value as there is no append function in string why because its imutable 
        else:
            big = letter.upper()
#             print(big)
            y = y + big # reassigning the y 

    return y

In [28]:
swap_case('I don\'t know she seems to be quite high maintainence')

"i DON'T KNOW SHE SEEMS TO BE QUITE HIGH MAINTAINENCE"

In [ ]:
x = 'ABCDCDC'
y = 'CDC'
for i in range(len(x+1))

In [13]:
x = 'ABCDCDC'
y='CDC'
empty = []
for i in range(0,len(x)):
    if i < len(x) - (len(y)-1):
        empty.append(x[i:i+len(y)])
print(empty) 
empty.count('CDC')

['ABC', 'BCD', 'CDC', 'DCD', 'CDC']


2

In [22]:
s = 'qA2'
for i in s:
    if i.isdigit() == True:
        z = str(i)
z.isdigit()    
# for k in s:
#         if k.isdigit() == True:
#             print('True')
#             #break
#         else:
#             print('False')
#             #break 
        

True

In [21]:
y = 'Deepu'
y.find('u')

4

In [11]:
z = '2-1'
type(eval(z))

int

In [19]:
s = 'qA'
for i in s:
    if i.isdigit() == True:
        a = (i)
a.isdigit() 

NameError: name 'a' is not defined

In [49]:
s = 'qA2'

for i in s:
    while i.isdigit() == True:
        print("True")
        
        
        
print(False)

            

True
False


In [28]:
s.isdigit()

False

In [6]:

all([12,2,2,2,'true'])

True

In [8]:
string = 'qA2'
string.isalnum()


True

In [11]:
string.isalpha()

False

In [17]:
y = []
for i in string:
    y.append(i.isalpha())
print(y)
print(False in y)
    

[True, True, False]
True


In [18]:
y = []
for i in string:
    y.append(i.isdigit())
print(y)
print(False in y)
    

[False, False, True]
True


In [19]:
y = []
for i in string:
    y.append(i.isupper())
print(y)
print(False in y)

[False, True, False]
True


In [ ]:
string.

In [2]:
import numpy as np

In [3]:
l1 =[[1,2],[1,2],[1,2],[1,2]]
array1 = np.array(l1)
print(array1)

[[1 2]
 [1 2]
 [1 2]
 [1 2]]


In [5]:
l2 = [[3,4],[3,4],[3,4]]
array2 = np.array(l2)
array2

array([[3, 4],
       [3, 4],
       [3, 4]])

In [12]:
np.concatenate((array1,array2),axis = 0)

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [3, 4],
       [3, 4],
       [3, 4]])

In [13]:
val1 = int(input()).strip()
va1 = eval(val1)
for i in range(val1[0]+val[-1]):
    values = int(input())
    print(values)


4 3 2


ValueError: invalid literal for int() with base 10: '4 3 2'

In [33]:
val1 = input().strip()
val = val1.split(' ')
master_input = [eval(i) for i in val]
list1 = []
for i in range(master_input[0]): #master_input[0]+master_input[1]
    mat_val = input().strip()
    inti=[eval(a) for a in mat_val.split(' ')]
    list1.append(inti)
#print(list1)    
array1 = np.array(list1)
list2=[]
for j in range(master_input[1]):
    mat_val2 = input().strip()
    inti2 = [eval(b) for b in mat_val2.split(' ')]
    list2.append(inti2)
array2 = np.array(list2)
print(np.concatenate((array1,array2)))
    
    

4 3 2
1 2
1 2
1 2
1 2
 3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [26]:
type(eval('5'))

int

In [1]:
import numpy as np
np.set_printoptions(legacy='1.13')
val = input().strip()
user_input = {eval(i) for i in val.split(' ')}
arg = list(user_input)
array = np.identity(arg[-1])
print(array)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [4]:
import numpy as np
np.set_printoptions(legacy='1.13')
val = input().strip()
user_input = [eval(i) for i in val.split(' ')]
print(user_input.unique())
# arg = list(user_input)
# array = np.identity(arg[-1])
# print(array)

2 3


AttributeError: 'list' object has no attribute 'unique'

In [10]:
a = [3,3]
ar = np.array(a)
ar.u

AttributeError: 'numpy.ndarray' object has no attribute 'u'

In [11]:
tuple(np.unique(ar))

(3,)

In [44]:
val = input().strip()
a = tuple(eval(i) for i in val.split(' '))
print(a)
ip = tuple(list(set(a)))
print(ip)
if len(ip) == 1:
    print(np.identity(ip[0]))
else:
    print(ip)
    print(np.eye(a[0],a[1]))
        
        

3 3
(3, 3)
(3,)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
t = (5,3)
np.eye(t[0],t[1])


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
val = input().strip()
a = [eval(i) for i in val.split(' ')]
#print(a)
for i in range(a[0]):
    mat = input().strip()
    mat_val = [eval(item) for item in mat.split(' ')]
    array1 = np.array(mat_val,ndmin = 2)
    #print(array1)  
for j in range(a[0]):
    mat2 = input().strip()
    mat_val2 = [eval(item) for item in mat2.split(' ')]
    array2 = np.array(mat_val2, ndmin = 2)
    #print(array2)      
print(np.add(array1,array2))
print(np.subtract(array1,array2))
print(np.multiply(array1,array2))
print(np.around(np.divide(array1,array2)))
print(np.mod(array1,array2))
print(np.power(array1,array2))   

2 4
1 2 3 4
1 2 3 4
5 6 7 7
5 6 7 7
[[ 6  8 10 11]]
[[-4 -4 -4 -3]]
[[ 5 12 21 28]]
[[0. 0. 0. 1.]]
[[1 2 3 4]]
[[    1    64  2187 16384]]


In [79]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
print(np.add(array1,array2))
print(np.subtract(array1,array2))
print(np.multiply(array1,array2))
print(np.divide(array1,array2).astype(int))
print(np.mod(array1,array2))
print(np.power(array1,array2))



[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0 0 0 0]
[1 2 3 4]
[    1    64  2187 65536]


In [74]:
np.array([1,2,3,4],ndmin=2)

array([[1, 2, 3, 4]])

In [4]:
val = input().strip()
a = [eval(i) for i in val.split(' ')]
#print(a)
emp1 = []
for i in range(a[0]):
    mat = input().strip()
    mat_val = [eval(item) for item in mat.split(' ')]
    emp1.append(mat_val)
    array1 = np.array(emp1)
    #print(array1)
emp2 =[]
for j in range(a[0]):
    mat2 = input().strip()
    mat_val2 = [eval(item) for item in mat2.split(' ')]
    emp2.append(mat_val2)
    array2 = np.array(emp2)
    #print(array2)      
print(np.add(array1,array2))
print(np.subtract(array1,array2))
print(np.multiply(array1,array2))
print(np.around(np.divide(array1,array2)))
print(np.mod(array1,array2))
print(np.power(array1,array2))  

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0. 0. 0. 0.]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [2]:
import numpy as np

In [7]:
val = input().strip()
ip = [eval(i) for i in val.split(' ')]
array = np.array(ip)
print(np.floor(array))
print(np.ceil(array))
print(np.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [17]:
val = input().strip()
ip = [eval(i) for i in val.split(' ')]
y = []
for i in range(ip[0]):
    ipa = input().strip()
    ui=[eval(j) for j in ipa.split(' ')]
    y.append(ui)
array = np.array(y) 
p=(np.sum(array,axis = 0))

print(np.product(p))

2 2
1 2
3 2
16


In [14]:
np.prod([[1,2],[3,2]])

12

In [15]:
l = [4,4]
np.prod(l)

16

In [22]:
val = input().strip()
ip = [eval(i) for i in val.split(' ')]
y = []
for i in range(ip[0]):
    ipa = input().strip()
    ui=[eval(j) for j in ipa.split(' ')]
    y.append(ui)
array = np.array(y) 
print(array)
l=np.min(array,axis = 1)
print(np.max(l,axis = 0))

4 2
2 5
3 7
1 3
4 0
[[2 5]
 [3 7]
 [1 3]
 [4 0]]
0


In [28]:
val = input().strip()
np.set_printoptions(legacy='1.13')
ip = [eval(i) for i in val.split(' ')]
y = []
for i in range(ip[0]):
    ipa = input().strip()
    ui=[eval(j) for j in ipa.split(' ')]
    y.append(ui)
array = np.array(y) 
print(array)
print(np.mean(array,axis = 1))
print(np.var(array,axis = 0))
print(round(np.std(array),11))


2 2
1 2
3 4
[[1 2]
 [3 4]]
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [32]:
a=np.ones((2,2))*1.1

In [33]:
np.linalg.det(a)

0.0

In [35]:
val = input().strip()
np.set_printoptions(legacy='1.13')
ip = [eval(i) for i in val.split(' ')]
y = []
for i in range(ip[0]):
    ipa = input().strip()
    ui=[eval(j) for j in ipa.split(' ')]
    y.append(ui)
array = np.array(y) 
#print(array)
print(np.linalg.det(array))

2
1.1 1.1
1.1 1.1
0.0
