In [8]:
import numpy as np 
import pandas as pd

In [15]:
np.random.seed(21)
array = np.random.randint(10,99, size = (10,4))
print(array)

[[83 89 66 14]
 [58 45 70 84]
 [82 73 54 71]
 [58 94 69 30]
 [86 66 51 15]
 [28 80 60 66]
 [58 63 15 90]
 [45 43 22 92]
 [25 16 94 38]
 [19 90 10 15]]


In [17]:
df = pd.DataFrame(array, index = ['a','b','c','d','e','f','g','h','i','j'], columns = ['class 1','class 2','class 3', 'class 4'])

In [18]:
df

class 1  class 2  class 3  class 4
a       83       89       66       14
b       58       45       70       84
c       82       73       54       71
d       58       94       69       30
e       86       66       51       15
f       28       80       60       66
g       58       63       15       90
h       45       43       22       92
i       25       16       94       38
j       19       90       10       15

In [19]:
def dif_per(cola,colb):
    if cola > colb:
        dif = cola - colb
    else:
        dif = colb - cola
    
    y = round(dif/cola*100,2)
    return y    

In [21]:
dif_per(23,34)

47.83

In [8]:
df.apply(dif_per,axis=1)

TypeError: dif_per() missing 1 required positional argument: 'colb'

In [22]:
def y(cl):
    return cl[2] + cl[3]

In [26]:
df['addy']=df.apply(y,axis=1)

In [27]:
df

class 1  class 2  class 3  class 4  addy
a       83       89       66       14    80
b       58       45       70       84   154
c       82       73       54       71   125
d       58       94       69       30    99
e       86       66       51       15    66
f       28       80       60       66   126
g       58       63       15       90   105
h       45       43       22       92   114
i       25       16       94       38   132
j       19       90       10       15    25

# Lets make a practical example 

In [9]:
def profit_percentage(x):
    profit = x[1] - x[0]
    pp = profit/x[0] * 100
    return pp

In [10]:
df.apply(profit_percentage,axis = 1)
df['profit_percentage'] = df.apply(profit_percentage,axis = 1)
df

class 1  class 2  class 3  class 4  profit_percentage
a       24       53       63       93         120.833333
b       38       10       59       61         -73.684211
c       96       10       50       44         -89.583333
d       93       87       95       18          -6.451613
e       85       77       29       57          -9.411765
f       87       54       17       80         -37.931034
g       10       69       56       48         590.000000
h       19       20       25       35           5.263158
i       49       89       90       14          81.632653
j       57       79       68       20          38.596491

**This is basically using functions with out using lambda functions**

Now since I am returning from break lets do it again to understand

In [11]:
# lets do error handling as well 
new_array = np.array([29,84,70,96])
new_array

array([29, 84, 70, 96])

In [42]:
np.random.seed(32)
array=np.random.randint(1,50, size = (10,5))
df = pd.DataFrame(array,columns = ['Physics','chemistry','Maths','English','Physical_education'],index = ['Deepu','Sachin','Rahul'\
                                ,'Prashant','Vikas','Chittranjan','Pawan','Amit','Ashok','Bhanu'])
display(df)

Physics  chemistry  Maths  English  Physical_education
Deepu             24         44      6       25                  20
Sachin             8         26      4       38                  43
Rahul             10          5     12       18                   4
Prashant           2         35     36       25                  43
Vikas             19         11     21       37                  37
Chittranjan        6         39     14       12                  12
Pawan             27         30     30       27                  48
Amit               1         12      7       47                  31
Ashok              5         42     31       17                  20
Bhanu             38         11     36       46                  25

In [53]:
# lets write a fucntion to calculate percentage of every student 
def percentage(col):
    marks_obtained = col[0] + col[1] + col[2] + col[3] + col[4]
    percent = (marks_obtained/250)*100
    percentage = round(percent,2)
    return percentage

# When working with funciton on df it does not matter what parameter you set when you are defining your function. because when
# when funtion enters the dataframe the the parameter which you had set while defining the function will now be the dataframe
# so if while defining it was col(the paramenter) and in the later part of the code you are calling col[1] so when the function
# has entered the dataframe it will refere to it as dataframe[1] i.e 2nd coloum of the dataframe.

In [54]:
df['percentage']=df.apply(percentage,axis = 1)

In [45]:
df

Physics  chemistry  Maths  English  Physical_education  \
Deepu             24         44      6       25                  20   
Sachin             8         26      4       38                  43   
Rahul             10          5     12       18                   4   
Prashant           2         35     36       25                  43   
Vikas             19         11     21       37                  37   
Chittranjan        6         39     14       12                  12   
Pawan             27         30     30       27                  48   
Amit               1         12      7       47                  31   
Ashok              5         42     31       17                  20   
Bhanu             38         11     36       46                  25   

             percentage  
Deepu              47.6  
Sachin             47.6  
Rahul              19.6  
Prashant           56.4  
Vikas              50.0  
Chittranjan        33.2  
Pawan              64.8  
Amit               39.2  
Ashok              46.0  
Bhanu              62.4

In [47]:
# lets write a fucntion to calculate percentage of every student 
# while writing the funciton to call the columns you can use df.column_name 
# Note df is general does not make any sense but it does only when the function enters the dataframe 
# here you can also write col.Physics , col.chemistry , col.Maths , col.English , col.Physical_education the result will be same
def using_coloumn_name(df):
    marks_obtained = df.Physics + df.chemistry + df.Maths + df.English + df.Physical_education
    percent = (marks_obtained/250)*100
    percentage = round(percent,2)
    return percentage

In [55]:
df['Percentage_using_conlumn_name']=df.apply(using_coloumn_name, axis = 1) # Please define the axis

In [50]:
df

Physics  chemistry  Maths  English  Physical_education  \
Deepu             24         44      6       25                  20   
Sachin             8         26      4       38                  43   
Rahul             10          5     12       18                   4   
Prashant           2         35     36       25                  43   
Vikas             19         11     21       37                  37   
Chittranjan        6         39     14       12                  12   
Pawan             27         30     30       27                  48   
Amit               1         12      7       47                  31   
Ashok              5         42     31       17                  20   
Bhanu             38         11     36       46                  25   

             percentage  Percentage_using_conlumn_name  
Deepu              47.6                           47.6  
Sachin             47.6                           47.6  
Rahul              19.6                           19.6  
Prashant           56.4                           56.4  
Vikas              50.0                           50.0  
Chittranjan        33.2                           33.2  
Pawan              64.8                           64.8  
Amit               39.2                           39.2  
Ashok              46.0                           46.0  
Bhanu              62.4                           62.4

In [83]:
# let do it using lamda function
def per_gen(a,b,c,d,e): # as far as i have seen the parameter datatype need not be defined
    total = a + b + c + d + e
    percent = (total/250)*100
    p = round(percent,2)
    return p

In [84]:
per_gen(38,11,36,46,25)

62.4

In [111]:
df['launda'] = df.apply(lambda x:per_gen(x['Physics'],x['chemistry'],x['Maths'],x['English'],x['Physical_education']), axis = 1)

In [95]:
u=lambda a,b,c,d,e:a+b+c+d+e
u(1,2,3,4,5)

15

In [112]:
df

Physics  chemistry  Maths  English  Physical_education  \
Deepu             24         44      6       25                  20   
Sachin             8         26      4       38                  43   
Rahul             10          5     12       18                   4   
Prashant           2         35     36       25                  43   
Vikas             19         11     21       37                  37   
Chittranjan        6         39     14       12                  12   
Pawan             27         30     30       27                  48   
Amit               1         12      7       47                  31   
Ashok              5         42     31       17                  20   
Bhanu             38         11     36       46                  25   

             percentage  Percentage_using_conlumn_name  launda  
Deepu              47.6                           47.6    47.6  
Sachin             47.6                           47.6    47.6  
Rahul              19.6                           19.6    19.6  
Prashant           56.4                           56.4    56.4  
Vikas              50.0                           50.0    50.0  
Chittranjan        33.2                           33.2    33.2  
Pawan              64.8                           64.8    64.8  
Amit               39.2                           39.2    39.2  
Ashok              46.0                           46.0    46.0  
Bhanu              62.4                           62.4    62.4

In [116]:
y = lambda x : per_gen(12,12,2,32,12)
print(y)


<function <lambda> at 0x000001780699D8B0>


In [117]:
y = lambda x : per_gen(12,12,2,32,12)
y(1,2,3,3,4)

TypeError: <lambda>() takes 1 positional argument but 5 were given

In [1]:
# This was when there was not zero value in the dataframe what if there was a zero value 

In [2]:
import numpy as np
import pandas as pd

In [13]:
np.random.seed(1)
data = np.random.randint(0,20,size = (10,2))
df = pd.DataFrame(data,columns = ['cost_price','selling_price'])
df

cost_price  selling_price
0           5             11
1          12              8
2           9             11
3           5             15
4           0             16
5           1             12
6           7             13
7           6             18
8           5             18
9          11             10

lets use lambda function 

In [31]:
def profit_percent(a,b):
    percent = ((b-a)/a)*100
    return round(percent,2)

In [15]:
profit_percent(100,120)

20.0

In [16]:
profit_percent(0,100)

ZeroDivisionError: division by zero

In [19]:
df.apply(lambda x: profit_percent(x[0],x[1]),axis = 1)

C:\Users\Deepu\AppData\Local\Temp\ipykernel_3184\1523864537.py:2: RuntimeWarning: divide by zero encountered in long_scalars
  percent = ((b-a)/a)*100


0     120.000000
1     -33.333333
2      22.222222
3     200.000000
4            inf
5    1100.000000
6      85.714286
7     200.000000
8     260.000000
9      -9.090909
dtype: float64

In [20]:
# there is a problem first lets try to solve it in the funciton only using error handling 

In [21]:
def profit_percent_1(a,b):
    try:
        percent = ((b-a)/a)* 100
        return percent
    except:
        percent = np.nan
        return percent

In [23]:
profit_percent_1(100,128)

28.000000000000004

In [24]:
profit_percent_1(0,19)

nan

In [25]:
df.apply(lambda x:profit_percent_1(x[0],x[1]),axis =1)
# the problem is still not solved this solves the probelm in imdb data set though

C:\Users\Deepu\AppData\Local\Temp\ipykernel_3184\3930674006.py:3: RuntimeWarning: divide by zero encountered in long_scalars
  percent = ((b-a)/a)* 100


0     120.000000
1     -33.333333
2      22.222222
3     200.000000
4            inf
5    1100.000000
6      85.714286
7     200.000000
8     260.000000
9      -9.090909
dtype: float64

# scrutinize the below line of code carefully 

In [28]:
df.apply(lambda x: profit_percent(x[0],x[1]) if x[0] != 0 else np.nan,axis = 1)

0     120.000000
1     -33.333333
2      22.222222
3     200.000000
4            NaN
5    1100.000000
6      85.714286
7     200.000000
8     260.000000
9      -9.090909
dtype: float64

In [32]:
df['profit_percent'] = df.apply(lambda x: profit_percent(x[0],x[1]) if x[0] != 0 else np.nan,axis = 1)

In [33]:
df

cost_price  selling_price  profit_percent
0           5             11          120.00
1          12              8          -33.33
2           9             11           22.22
3           5             15          200.00
4           0             16             NaN
5           1             12         1100.00
6           7             13           85.71
7           6             18          200.00
8           5             18          260.00
9          11             10           -9.09

**When we use lambda in apply it basically iterates the rows if we don't use the lamda and do directly it will take a series** 

In [39]:
df.apply(profit_percent(df.cost_price,df.selling_price),axis = 1) # takes as series 

AssertionError: 

# summarize the lambda function and apply function tomorrow

So first there are some syntax which you have to folow and can't do much about it 

Lambda function is basically a anonynomous function which can have multiple arugments and only one expression 

Now when it comes to code on dataframe you can do it in two ways one is to write customize function this way you are picking 
an element from the series one by one and then applying the code 
The other way is throught lambda funciton , this funciton when used on dataframe iterates the series that is it picks one 
element form the series and then apply codes on it 
the other part of the function is unexplored right now 

In [4]:
x = lambda a: a*a # a lambda function which returns square of a number
x(2) # callng lambda function by the variable to which it is assigned

4

In [5]:
# lambda function with multiple arguments 
y = lambda a,b,c,d,e,f,g: a+b+c+d+e+f+g
y(1,2,3,4,5,6,6)

27

**lets apply lambda function on data set via customized functions**

In [9]:
pwd

'C:\\Users\\Deepu\\Documents\\My_Python_codes'

In [10]:
cd C:\\Users\\Deepu\\Downloads

C:\Users\Deepu\Downloads


In [11]:
df = pd.read_csv('imdb_data.csv')

In [12]:
df

id                              belongs_to_collection    budget  \
0        1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000   
1        2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000   
2        3                                                NaN   3300000   
3        4                                                NaN   1200000   
4        5                                                NaN         0   
...    ...                                                ...       ...   
2995  2996                                                NaN         0   
2996  2997                                                NaN         0   
2997  2998                                                NaN  65000000   
2998  2999                                                NaN  42000000   
2999  3000                                                NaN  35000000   

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]   
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   
2                         [{'id': 18, 'name': 'Drama'}]   
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...   
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...   
...                                                 ...   
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...   
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...   
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...   
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...   

                               homepage    imdb_id original_language  \
0                                   NaN  tt2637294                en   
1                                   NaN  tt0368933                en   
2     http://sonyclassics.com/whiplash/  tt2582802                en   
3            http://kahaanithefilm.com/  tt1821480                hi   
4                                   NaN  tt1380152                ko   
...                                 ...        ...               ...   
2995                                NaN  tt0109403                en   
2996                                NaN  tt2364975                sv   
2997                                NaN  tt0116908                en   
2998     http://www.alongcamepolly.com/  tt0343135                en   
2999   http://www.abductionthefilm.com/  tt1600195                en   

                                original_title  \
0                       Hot Tub Time Machine 2   
1     The Princess Diaries 2: Royal Engagement   
2                                     Whiplash   
3                                      Kahaani   
4                                         마린보이   
...                                        ...   
2995                                   Chasers   
2996                               Vi är bäst!   
2997                   The Long Kiss Goodnight   
2998                          Along Came Polly   
2999                                 Abduction   

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...   
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...   
2     Under the direction of a ruthless instructor, ...   64.299990  ...   
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...   
4     Marine Boy is the story of a former national s...    1.148070  ...   
...                                                 ...         ...  ...   
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...   
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...   
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...   
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...   
2999  A young man sets out to uncover the truth abou...   10.512109  ...   

     release_date r

In [16]:
def c_profit(a):
    '''the data has zero hence do error handling also'''
    try:
        profit = ((a.budget-a.revenue)/a.budget)*100
        return round(profit,2)
    except:
        return np.nan # return np.nan when budget is zero

In this code below you must be wondering that why have I not passed the arguments in the function c_profit well the argument is already taken care while define the funciton 

In [18]:
df.apply(c_profit,axis = 1)

0         12.04
1       -137.87
2       -296.73
3      -1233.33
4           NaN
         ...   
2995        NaN
2996        NaN
2997     -37.63
2998    -309.44
2999    -134.53
Length: 3000, dtype: float64

**lets use lambda function to apply the same operation**
Note I am again mentioning that the lambdda function basically iterates the series 

In [21]:
def profit_percent(cp,sp):
    try:
        profit = ((sp-cp)/cp)*100
        return round(profit,2)
    except:
        profit = np.nan
        return profit
        

In [22]:
profit_percent(100,120)

20.0

In [24]:
profit_percent(0,120)

nan

In [25]:
df.apply(lambda x: profit_percent(x.budget,x.revenue),axis =1)

0        -12.04
1        137.87
2        296.73
3       1233.33
4           NaN
         ...   
2995        NaN
2996        NaN
2997      37.63
2998     309.44
2999     134.53
Length: 3000, dtype: float64

Now the thrid case where we are handling the error in the apply code only 

In [27]:
def profit_percent(cp,sp):
    profit = ((sp-cp)/cp)*100
    return round(profit)

In [29]:
# agian this is a syntax and you can not do much about it 
df.apply(lambda x: profit_percent(x.budget,x.revenue) if x.budget != 0 else np.nan,axis = 1)

0        -12.0
1        138.0
2        297.0
3       1233.0
4          NaN
         ...  
2995       NaN
2996       NaN
2997      38.0
2998     309.0
2999     135.0
Length: 3000, dtype: float64

Unexplored part 

In [31]:
def caps(a):
    return a.upper()

In [37]:
''' note here when you are doing df.column_name.apply you don't have to use the arguent axis = 1
because you are already defining the name of the column you want to used the code on '''
df.original_title.apply(caps)

0                         HOT TUB TIME MACHINE 2
1       THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT
2                                       WHIPLASH
3                                        KAHAANI
4                                           마린보이
                          ...                   
2995                                     CHASERS
2996                                 VI ÄR BÄST!
2997                     THE LONG KISS GOODNIGHT
2998                            ALONG CAME POLLY
2999                                   ABDUCTION
Name: original_title, Length: 3000, dtype: object

You can use inbuit function on dataframe provided by pandas and you can create some new function and use them by apply method

In [39]:
# you can run the same function using lambda function 
df.apply(lambda x: x.original_title.upper(),axis = 1)

0                         HOT TUB TIME MACHINE 2
1       THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT
2                                       WHIPLASH
3                                        KAHAANI
4                                           마린보이
                          ...                   
2995                                     CHASERS
2996                                 VI ÄR BÄST!
2997                     THE LONG KISS GOODNIGHT
2998                            ALONG CAME POLLY
2999                                   ABDUCTION
Length: 3000, dtype: object

One more method which comes in handy to find the index of the columns in dataframe is

In [44]:
df.columns.get_loc('budget')

2

In [43]:
df.columns.get_loc('revenue')

22

So when writing the customize funciton you can directy use index as well 

# There are 3 ways to use apply methods
## 1.df.column_name.apply(general_function_name) 
## here you are directly applying the funciton on the column , no need to mention axis in that case this comes in handy when you have to operate on a single column only 
## 2.df.apply(lambda x: function(x.column),axis = 1)
## 3.df.apply(custom_function,axis = 1)